import { Lesson, Track } from '@/types';

export const tracks: Track[] = [
  { id: 'prompt-engineering', title: 'Prompt Engineering & LLM Basics', description: 'Master the art of communicating with AI.', icon: 'message-square' },
  { id: 'ai-coding', title: 'AI Coding & Vibe Coding', description: 'Build full apps using AI coding agents.', icon: 'code' },
  { id: 'rag-systems', title: 'RAG Systems & Knowledge Assistants', description: 'Connect AI to your own data.', icon: 'database' },
  { id: 'agentic-ai', title: 'Agentic AI & Multi-Agent Systems', description: 'Build autonomous AI teams.', icon: 'users' },
  { id: 'systems-thinking', title: 'Software Systems Thinking & Architecture', description: 'Design complex AI-powered systems.', icon: 'layout' },
  { id: 'mlops', title: 'MLOps, CI/CD & Production Deployment', description: 'Deploy and monitor AI in the real world.', icon: 'rocket' },
];

export const lessons: Lesson[] = [
  // --- TRACK: PROMPT ENGINEERING ---
  {
    id: 'pe-1',
    title: 'Prompt Engineering Fundamentals',
    description: 'Learn specificity, context, and formatting.',
    track: 'prompt-engineering',
    difficulty: 'beginner',
    content: '# Prompt Engineering\nMastering the basics of communicating with LLMs.',
    tasks: [{ id: 'pe1', description: 'Test different temperatures in Playground', completed: false }],
  },

  // --- TRACK: AI CODING & VIBE CODING ---
  {
    id: 'vc-website',
    title: 'Personal Website with AI Digital Twin',
    description: 'Build your digital home using vibe coding.',
    track: 'ai-coding',
    difficulty: 'beginner',
    content: '# Project: Personal Website\nUse AI coding agents to build a portfolio.',
    tasks: [{ id: 'vc1', description: 'Create hero section', completed: false }],
  },
  {
    id: 'vc-chatbot',
    title: 'Simple Chatbot with Vibe Coding',
    description: 'Create a conversational interface from scratch.',
    track: 'ai-coding',
    difficulty: 'beginner',
    content: '# Project: Simple Chatbot\nBuilding interfaces with natural language.',
    tasks: [{ id: 'vc2', description: 'Implement message bubbles', completed: false }],
  },
  {
    id: 'vc-kanban',
    title: 'Kanban Board with AI Assistance',
    description: 'Build a project management tool.',
    track: 'ai-coding',
    difficulty: 'beginner',
    content: '# Project: Kanban Board\nDrag and drop tasks with AI-generated logic.',
    tasks: [{ id: 'vc3', description: 'Add board columns', completed: false }],
  },
  {
    id: 'vc-notes',
    title: 'AI Note-taking App',
    description: 'Develop a note-taking app using Cursor.',
    track: 'ai-coding',
    difficulty: 'beginner',
    content: '# Project: Note-taking App\nManage your ideas with an AI-powered editor.',
    tasks: [{ id: 'vc4', description: 'Implement local storage', completed: false }],
  },
  {
    id: 'vc-doc-gen',
    title: 'AI Document Generator',
    description: 'Create a document generator using AI workflows.',
    track: 'ai-coding',
    difficulty: 'beginner',
    content: '# Project: Document Generator\nAutomate document creation.',
    tasks: [{ id: 'vc5', description: 'Generate PDF from prompt', completed: false }],
  },
  {
    id: 'vc-legal',
    title: 'SaaS Legal Assistant',
    description: 'Drafts legal documents + PDF download.',
    track: 'ai-coding',
    difficulty: 'intermediate',
    content: '# Project: SaaS Legal Assistant\nComplex document generation SaaS.',
    tasks: [{ id: 'vc6', description: 'Implement document templates', completed: false }],
  },

  // --- TRACK: RAG SYSTEMS ---
  {
    id: 'rag-personal',
    title: 'RAG-based Personal Knowledge Assistant',
    description: 'Chat with your own documents.',
    track: 'rag-systems',
    difficulty: 'intermediate',
    content: '# Project: RAG Assistant\nUse the `ollama_client.py` helper to power your RAG assistant with your local model.',
    tasks: [
      { id: 'r1', description: 'Import ollama_client in your project', completed: false },
      { id: 'r2', description: 'Index local files', completed: false }
    ],
  },
  {
    id: 'rag-company',
    title: 'RAG Knowledge Worker (Company Expert)',
    description: 'Enterprise-grade RAG system.',
    track: 'rag-systems',
    difficulty: 'advanced',
    content: '# Project: Company Expert\nHigh-accuracy retrieval for technical docs.',
    tasks: [{ id: 'r2', description: 'Optimize vector retrieval', completed: false }],
  },

  // --- TRACK: AGENTIC AI ---
  {
    id: 'ag-research',
    title: 'Multi-Agent System for Research',
    description: 'Orchestrate agents for deep analysis.',
    track: 'agentic-ai',
    difficulty: 'intermediate',
    content: '# Project: Research Team\nUse your local Qwen model to orchestrate multiple specialized AI workers.',
    tasks: [
      { id: 'a1', description: 'Test ollama_client.py connection', completed: false },
      { id: 'a2', description: 'Define agent roles', completed: false }
    ],
  },
  {
    id: 'ag-deal',
    title: 'Autonomous Deal Spotting System',
    description: 'Agents that find deals and notify you.',
    track: 'agentic-ai',
    difficulty: 'advanced',
    content: '# Project: Deal Spotter\nReal-world automation with AI agents.',
    tasks: [{ id: 'a2', description: 'Connect scraping tool', completed: false }],
  },
  {
    id: 'ag-support',
    title: 'Multi-modal Customer Support Agent',
    description: 'UI + function calling support.',
    track: 'agentic-ai',
    difficulty: 'intermediate',
    content: '# Project: Support Agent\nHandling diverse customer requests.',
    tasks: [{ id: 'a3', description: 'Implement function calling', completed: false }],
  },

  // --- TRACK: SYSTEMS THINKING ---
  {
    id: 'st-brochure',
    title: 'AI-Powered Brochure Generator',
    description: 'Web scraping + intelligent navigation.',
    track: 'systems-thinking',
    difficulty: 'intermediate',
    content: '# Project: Brochure Generator\nTransforming raw web data into marketing copy.',
    tasks: [{ id: 's1', description: 'Scrape company website', completed: false }],
  },
  {
    id: 'st-minutes',
    title: 'Meeting Minutes Generator',
    description: 'From audio/text to actionable items.',
    track: 'systems-thinking',
    difficulty: 'intermediate',
    content: '# Project: Minutes Generator\nSummarization and task extraction.',
    tasks: [{ id: 's2', description: 'Extract action items', completed: false }],
  },
  {
    id: 'st-optimizer',
    title: 'AI Code Optimizer Tool',
    description: 'Python -> optimized C++ converter (60,000x boost).',
    track: 'systems-thinking',
    difficulty: 'advanced',
    content: '# Project: Code Optimizer\nArchitecture for extreme performance.',
    tasks: [{ id: 's3', description: 'Implement C++ generation', completed: false }],
  },
  {
    id: 'st-prediction',
    title: 'Product Price Prediction',
    description: 'Using frontier models.',
    track: 'systems-thinking',
    difficulty: 'advanced',
    content: '# Project: Price Prediction\nPredictive modeling with LLMs.',
    tasks: [{ id: 's4', description: 'Evaluate model accuracy', completed: false }],
  },
  {
    id: 'st-fine-tune',
    title: 'Fine-tuned Model for Prediction',
    description: 'Fine-tune an open-source model for specific tasks.',
    track: 'systems-thinking',
    difficulty: 'advanced',
    content: '# Project: Fine-tuning\nLearning QLoRA and model optimization.',
    tasks: [{ id: 's5', description: 'Fine-tune Qwen 2.5', completed: false }],
  },

  // --- TRACK: MLOPS & CI/CD ---
  {
    id: 'ml-terminal-project',
    title: 'Terminal-based Project Runner',
    description: 'Build and run a project using terminal commands.',
    track: 'mlops',
    difficulty: 'beginner',
    content: '# Project: Terminal Runner\nMastering the command line for automation.',
    tasks: [{ id: 'm0', description: 'Run build script in terminal', completed: false }],
  },
  {
    id: 'ml-vc',
    title: 'Version Control for AI Projects',
    description: 'Set up Git and collaborative workflows.',
    track: 'mlops',
    difficulty: 'beginner',
    content: '# Project: Version Control\nThe foundation of production engineering.',
    tasks: [{ id: 'm1', description: 'Initialize git repo', completed: false }],
  },
  {
    id: 'ml-tests',
    title: 'Automated Testing for AI',
    description: 'Create basic testing workflows.',
    track: 'mlops',
    difficulty: 'intermediate',
    content: '# Project: Automated Testing\nEnsuring AI outputs stay reliable.',
    tasks: [{ id: 'm2', description: 'Write first prompt test', completed: false }],
  },
  {
    id: 'ml-deploy',
    title: 'Deploy to Free Hosting',
    description: 'Take your AI tool live.',
    track: 'mlops',
    difficulty: 'beginner',
    content: '# Project: Deployment\nMaking your tool accessible to the world.',
    tasks: [{ id: 'm3', description: 'Link to hosting provider', completed: false }],
  },
  {
    id: 'ml-pipeline',
    title: 'Basic CI/CD Pipeline',
    description: 'Automate your deployments.',
    track: 'mlops',
    difficulty: 'intermediate',
    content: '# Project: CI/CD Pipeline\nAutomating the road to production.',
    tasks: [{ id: 'm4', description: 'Setup GitHub Actions', completed: false }],
  },

  // --- CAPSTONES ---
  {
    id: 'cap-1',
    title: 'Capstone 1: AI Digital Twin',
    description: 'Complete representative Digital Twin.',
    track: 'systems-thinking',
    difficulty: 'advanced',
    content: '# Capstone: AI Digital Twin\nYour professional representative.',
    tasks: [{ id: 'c1', description: 'Final launch', completed: false }],
  },
  {
    id: 'cap-2',
    title: 'Capstone 2: Autonomous Research Team',
    description: 'Multi-agent team with terminal usage.',
    track: 'agentic-ai',
    difficulty: 'advanced',
    content: '# Capstone: Research Team\nAutonomous swarm for complex tasks.',
    tasks: [{ id: 'c2', description: 'Complete orchestration', completed: false }],
  },
  {
    id: 'cap-3',
    title: 'Capstone 3: Production-Ready RAG Assistant',
    description: 'With CI/CD deployment.',
    track: 'mlops',
    difficulty: 'advanced',
    content: '# Capstone: Production RAG\nScalable and reliable.',
    tasks: [{ id: 'c3', description: 'Deploy to production', completed: false }],
  },
  {
    id: 'cap-4',
    title: 'Capstone 4: AI Coding Agent Team',
    description: 'Create and maintain software projects.',
    track: 'ai-coding',
    difficulty: 'advanced',
    content: '# Capstone: Coding Agent Team\nBuilding software with swarms.',
    tasks: [{ id: 'c4', description: 'Implement auto-debug loop', completed: false }],
  },
  {
    id: 'cap-5',
    title: 'Capstone 5: Full AI-Powered SaaS Product',
    description: 'Agents, RAG, and automated deployment.',
    track: 'systems-thinking',
    difficulty: 'advanced',
    content: '# Capstone: SaaS Product\nThe ultimate end-to-end project.',
    tasks: [{ id: 'c5', description: 'Acquire first test user', completed: false }],
  },
  {
    id: 'cap-trading',
    title: 'Capstone: Real-time Trading Workstation',
    description: 'Live data + AI Assistant.',
    track: 'ai-coding',
    difficulty: 'advanced',
    content: '# Capstone: Trading Workstation\nComplex real-time AI system.',
    tasks: [{ id: 'ct', description: 'Integrate market API', completed: false }],
  }
];
